# Generated by Django 4.0.3 on 2022-04-12 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_autore_post_post_author_post_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='distance',
        ),
    ]
