# Generated by Django 4.0.3 on 2022-04-18 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_remove_post_distance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customeruser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cordinates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
